### ISSUE TITLE
Replace stwcs.updatewcs with astropy.wcs

### ISSUE THREAD

**Issue by acviana** [STScI-Citizen-Science/MTPipeline#83]
http://astropy.readthedocs.org/en/latest/wcs/

**Comment by ktfhale** [comment]
Turns out there is no equivalent to the function `updatewcs()` from the `stwcs.updatewcs` module in the module `astropy.wcs`. Astropy's module seems to deal primarily with converting between various kinds of celestial coordinate systems. However, `updatewcs()` does a great deal more, apparently updating the headers of any images it processes with the latest calibration data. I don't think anything just within `astropy.wcs` can replace `stwcs.udpatewcs`, at least on its own.

**Comment by acviana** [comment]
I agree with your conclusion. I found out that `stwcs` can be installed with `pip` so we should update the `setup.py` file accordingly.
