### ISSUE TITLE
Testing CTE Correction on ACS Data

### ISSUE THREAD

**Issue by acviana** [STScI-Citizen-Science/MTPipeline#99]
The ACS data will require an additional step that the WFPC2 data does not, CTE correction.
- http://www.stsci.edu/hst/acs/software/CTE/

Pull a file from ACS from our archive area on `/astro/mtpipeline/` and see if you can get the software to run the CTE correction over each.

**Comment by ktfhale** [comment]
I'm examining the ACS CTE correction options. The page linked references a module called `PixCteCorr`, that looks like it can do what we want. However, there's also a whole software package for ACS called [`CALACS`](http://www.stsci.edu/hst/acs/performance/calacs_cte/calacs_cte.html), the documentation page of which is more recent. Both `CALACS` and `PixCteCorr` exist within the `acstools` module. [The `astrotools` documentation](http://ssb.stsci.edu/doc/stsci_python_dev/acstools.doc/acstools.pdf) lists them separately, but it appears that `CALACS` does CTE correction as an early step, in addition to other steps like cosmic ray rejection and drizzling. `CALACS` seems to be its own pipeline. Are there issues with our solar system data that prevents us from using it?

For the moment, I'll look int just using the function `PixCteCorr`.

EDIT: I see that `CALACS` is the standard pipeline for reducing ACS data. Since we haven't grabbed anything after the `_flt.fits` files for our own archive, I assume there's a reason we are foregoing it.

**Comment by ktfhale** [comment]
`PixCteCorr` only supports ACS WFC images. The random saturn images I got off of our ACS archive used the SBC detector instead, so `PixCteCorr` is not an option for some subset of our ACS data, unless we want to hack out the if-statement that checks to make sure the detector is WFC.

**Comment by ktfhale** [comment]
I went and talked to Max. A summary of what I heard from him:

We don't know what effects CTE correction has on images of planets, or other significantly extended sources. CTE correction was developed for point sources, like stars. When it comes to objects like comets and asteroids, which are somewhat starlike, the effect of CTE correction should be beneficial. But we should examine planetary images before and after CTE correction to see if there's actually an improvement, or if it's actually destructive.

CALACS is the first part of the ACS reduction pipeline, and seemingly deals with the hardware-based issues. Before it included CTE correction, its final output were `_flt.fits` files, which we have in our archive. After a new version was released that included CTE correction, its final outputs were `_flc.fits` files, which we don't have.

![Alt](http://www.stsci.edu/hst/acs/performance/calacs_cte/calacs2.png)

I'm going to request some `_flc.fits` from MAST, and compare them to the  `_flt.fits` files we have in our own archive.

**Comment by deustua** [comment]
Hi kevin,
With respect to ACS it is correct that the pipeline runs CTE correction only for the WFC.  However,  while not tested with point sources, i think there is a cte effect for extended sources, though perhaps more subtle.  it is also true that faint sources can 'disappear' in the absence of cte correction.  so testing is agood idea.  Check with Marco Chiaberge  and find out if anyone has considered CTE correction with the SBC. 

susana

**Comment by deustua** [comment]
also, MAST does apply automatically the cte correction for acs images.  it didn't used to, but does now.

**Comment by ktfhale** [comment]
It appears that the majority of our ACS data is not taken using WFC, the Wide Field Channel. The majority seems to be HRC - the High Resolution Channel, which makes sense for things like planetary observations. Because i/o takes a long time, I don't have an exact breakup of the files yet, but WFC files so far seem to be on the order of hundreds, whereas there are thousands and maybe tens of thousands of SMB HRC files, respectively. I'll know more exactly tomorrow.

**Comment by ktfhale** [comment]
Our ACS `_flt.fits` files have the following distribution over the three detectors:

WFC: 595 files
SMB: 8542 files
HRC: 9159 files

**Comment by acviana** [comment]
From Marco Chiaberge:

> We published an ISR back in 2009 that includes a photometric correction formula for the HRC.
> You can find it here: http://www.stsci.edu/hst/acs/documents/isrs/isr0901.pdf
> 
> Note that the correction for ACS/WFC in that ISR is NOT the most updated version, but it is still ok for pre-SM4 data. For post SM4 data, the best photometric correction formula is published in the following ISR: http://www.stsci.edu/hst/acs/documents/isrs/isr1205.pdf

**Comment by ktfhale** [comment]
For the reasons noted in [Ticket#100](https://github.com/STScI-Citizen-Science/MTPipeline/issues/100) for WFC3 data (limited applicability to our data, long computation times), we will probably not implement CTE correction into the pipeline. This ticket can be closed.
